stages:
  - publish
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:latest
  stage: publish
  services:
    - docker:dind
  script:
    - docker build -t $TAG_COMMIT -t $TAG_LATEST .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
    - docker push $TAG_LATEST
  only:
    - dev

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $SSH_KEY
    - apk update && apk add openssh-client
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$SERVER_IP "docker pull $TAG_COMMIT"
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$SERVER_IP "docker container rm -f coord-react || true"
    - ssh -i $SSH_KEY -o StrictHostKeyChecking=no $DEPLOYMENT_USER@$SERVER_IP "docker run -d -p 3000:3000 --name coord-react $TAG_COMMIT"
  environment:
    name: development
    url: http://dev.coord.uk
  only:
    - dev